import { ASRInput, ASRTranscript } from './asrTypes';
import { FileMissingError, AudioTooShortError, EngineCrashError } from './asrErrors';
import fs from 'fs';

/**
 * Faster-Whisper Interface
 * Runs transcription on the provided audio path.
 */
export async function runWhisperEngine(input: ASRInput): Promise<ASRTranscript> {
    const { callUuid, voiceCallId, recordingPath } = input;

    // 1. Validate File Existence
    if (!fs.existsSync(recordingPath)) {
        throw new FileMissingError(recordingPath);
    }

    // 2. Validate Duration (Simple size check as proxy for now, or use ffprobe later)
    const stats = fs.statSync(recordingPath);
    if (stats.size < 1024) { // Ignore files smaller than 1KB
        throw new AudioTooShortError();
    }

    console.log(`🎙️ [ASR ENGINE] Processing ${voiceCallId} (${callUuid})`);

    // --- MOCK FASTER-WHISPER EXECUTION ---
    // In production, this would use child_process to call `faster-whisper` CLI 
    // or a native binding.
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Simulate random crash for retry testing (10% chance)
    if (Math.random() < 0.1) {
        throw new EngineCrashError("Random engine failure triggered for testing");
    }

    return {
        callUuid,
        voiceCallId,
        language: 'en', // auto-detected in real engine
        text: "This is a high-quality transcription generated by faster-whisper.",
        engine: 'faster-whisper',
        createdAt: new Date().toISOString(),
        segments: [
            { start: 0.0, end: 2.0, text: "This is a" },
            { start: 2.0, end: 4.5, text: "high-quality transcription" },
            { start: 4.5, end: 6.0, text: "generated by faster-whisper." }
        ],
        asrStatus: 'COMPLETED'
    };
}
